# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20170730_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteId', models.IntegerField()),
                ('buy', models.DecimalField(decimal_places=10, max_digits=20)),
                ('sell', models.DecimalField(decimal_places=10, max_digits=20)),
                ('currency', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='CoinbaseHistory',
        ),
        migrations.DeleteModel(
            name='CoinhakoHistory',
        ),
        migrations.DeleteModel(
            name='ZebpayHistory',
        ),
    ]
