# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20170819_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bitcoinlivedata',
            old_name='lastDayMax',
            new_name='lastDayMaxBuy',
        ),
        migrations.RenameField(
            model_name='bitcoinlivedata',
            old_name='lastDayMin',
            new_name='lastDayMaxSell',
        ),
        migrations.RenameField(
            model_name='bitcoinlivedata',
            old_name='lastHourMax',
            new_name='lastDayMinBuy',
        ),
        migrations.RenameField(
            model_name='bitcoinlivedata',
            old_name='lastHourMin',
            new_name='lastDayMinSell',
        ),
        migrations.RenameField(
            model_name='bitcoinlivedata',
            old_name='lastMonthMax',
            new_name='lastHourMaxBuy',
        ),
        migrations.RenameField(
            model_name='bitcoinlivedata',
            old_name='lastMonthMin',
            new_name='lastHourMaxSell',
        ),
        migrations.RenameField(
            model_name='bitcoinlivedata',
            old_name='lastWeekMax',
            new_name='lastHourMinBuy',
        ),
        migrations.RenameField(
            model_name='bitcoinlivedata',
            old_name='lastWeekMin',
            new_name='lastHourMinSell',
        ),
        migrations.AddField(
            model_name='bitcoinlivedata',
            name='lastMonthMaxBuy',
            field=models.DecimalField(decimal_places=10, default=-1, max_digits=20),
        ),
        migrations.AddField(
            model_name='bitcoinlivedata',
            name='lastMonthMaxSell',
            field=models.DecimalField(decimal_places=10, default=-1, max_digits=20),
        ),
        migrations.AddField(
            model_name='bitcoinlivedata',
            name='lastMonthMinBuy',
            field=models.DecimalField(decimal_places=10, default=-1, max_digits=20),
        ),
        migrations.AddField(
            model_name='bitcoinlivedata',
            name='lastMonthMinSell',
            field=models.DecimalField(decimal_places=10, default=-1, max_digits=20),
        ),
        migrations.AddField(
            model_name='bitcoinlivedata',
            name='lastWeekMaxBuy',
            field=models.DecimalField(decimal_places=10, default=-1, max_digits=20),
        ),
        migrations.AddField(
            model_name='bitcoinlivedata',
            name='lastWeekMaxSell',
            field=models.DecimalField(decimal_places=10, default=-1, max_digits=20),
        ),
        migrations.AddField(
            model_name='bitcoinlivedata',
            name='lastWeekMinBuy',
            field=models.DecimalField(decimal_places=10, default=-1, max_digits=20),
        ),
        migrations.AddField(
            model_name='bitcoinlivedata',
            name='lastWeekMinSell',
            field=models.DecimalField(decimal_places=10, default=-1, max_digits=20),
        ),
    ]
