# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zebpayhistory',
            name='currency',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
