# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_zebpayhistory_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zebpayhistory',
            name='siteId',
        ),
    ]
