# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_zebpayhistory_siteid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zebpayhistory',
            name='buyFees',
        ),
        migrations.RemoveField(
            model_name='zebpayhistory',
            name='sellFees',
        ),
    ]
